<div id="listEmoji">
      <h2>Emoticons</h2>
      <p>
            <img title=":blush:" class="emoji" src="/assets/img/emoji/blush.png">
            <img title=":scream:" class="emoji" src="/assets/img/emoji/scream.png">
            <img title=":smirk:" class="emoji" src="/assets/img/emoji/smirk.png">
            <img title=":smiley:" class="emoji" src="/assets/img/emoji/smiley.png">
            <img title=":laughing:" class="emoji" src="/assets/img/emoji/laughing.png">
            <img title=":stuck_out_tongue_winking_eye:" class="emoji" src="/assets/img/emoji/stuck_out_tongue_winking_eye.png">
            <img title=":rage:" class="emoji" src="/assets/img/emoji/rage.png">
            <img title=":disappointed:" class="emoji" src="/assets/img/emoji/disappointed.png">
            <img title=":sob:" class="emoji" src="/assets/img/emoji/sob.png">
            <img title=":kissing_heart:" class="emoji" src="/assets/img/emoji/kissing_heart.png">
            <img title=":wink:" class="emoji" src="/assets/img/emoji/wink.png">
            <img title=":pensive:" class="emoji" src="/assets/img/emoji/pensive.png">
            <img title=":confounded:" class="emoji" src="/assets/img/emoji/confounded.png">
            <img title=":flushed:" class="emoji" src="/assets/img/emoji/flushed.png">
            <img title=":relaxed:" class="emoji" src="/assets/img/emoji/relaxed.png">
            <img title=":mask:" class="emoji" src="/assets/img/emoji/mask.png">
            <img title=":heart:" class="emoji" src="/assets/img/emoji/heart.png">
            <img title=":broken_heart:" class="emoji" src="/assets/img/emoji/broken_heart.png">
      </p>
      <h2>People</h2>
      <p>
            <img title=":bowtie:" class="emoji" src="/assets/img/emoji/bowtie.png">
            <img title=":smile:" class="emoji" src="/assets/img/emoji/smile.png">
            <img title=":laughing:" class="emoji" src="/assets/img/emoji/laughing.png">
            <img title=":blush:" class="emoji" src="/assets/img/emoji/blush.png">
            <img title=":smiley:" class="emoji" src="/assets/img/emoji/smiley.png">
            <img title=":relaxed:" class="emoji" src="/assets/img/emoji/relaxed.png">
            <img title=":smirk:" class="emoji" src="/assets/img/emoji/smirk.png">
            <img title=":heart_eyes:" class="emoji" src="/assets/img/emoji/heart_eyes.png">
            <img title=":kissing_heart:" class="emoji" src="/assets/img/emoji/kissing_heart.png">
            <img title=":kissing_closed_eyes:" class="emoji" src="/assets/img/emoji/kissing_closed_eyes.png">
            <img title=":flushed:" class="emoji" src="/assets/img/emoji/flushed.png">
            <img title=":relieved:" class="emoji" src="/assets/img/emoji/relieved.png">
            <img title=":satisfied:" class="emoji" src="/assets/img/emoji/satisfied.png">
            <img title=":grin:" class="emoji" src="/assets/img/emoji/grin.png">
            <img title=":wink:" class="emoji" src="/assets/img/emoji/wink.png">
            <img title=":wink2:" class="emoji" src="/assets/img/emoji/wink2.png">
            <img title=":stuck_out_tongue_winking_eye:" class="emoji" src="/assets/img/emoji/stuck_out_tongue_winking_eye.png">
            <img title=":stuck_out_tongue_closed_eyes:" class="emoji" src="/assets/img/emoji/stuck_out_tongue_closed_eyes.png">
            <img title=":grinning:" class="emoji" src="/assets/img/emoji/grinning.png">
            <img title=":kissing:" class="emoji" src="/assets/img/emoji/kissing.png">
            <img title=":kissing_smiling_eyes:" class="emoji" src="/assets/img/emoji/kissing_smiling_eyes.png">
            <img title=":stuck_out_tongue:" class="emoji" src="/assets/img/emoji/stuck_out_tongue.png">
            <img title=":sleeping:" class="emoji" src="/assets/img/emoji/sleeping.png">
            <img title=":worried:" class="emoji" src="/assets/img/emoji/worried.png">
            <img title=":frowning:" class="emoji" src="/assets/img/emoji/frowning.png">
            <img title=":anguished:" class="emoji" src="/assets/img/emoji/anguished.png">
            <img title=":open_mouth:" class="emoji" src="/assets/img/emoji/open_mouth.png">
            <img title=":grimacing:" class="emoji" src="/assets/img/emoji/grimacing.png">
            <img title=":confused:" class="emoji" src="/assets/img/emoji/confused.png">
            <img title=":hushed:" class="emoji" src="/assets/img/emoji/hushed.png">
            <img title=":expressionless:" class="emoji" src="/assets/img/emoji/expressionless.png">
            <img title=":unamused:" class="emoji" src="/assets/img/emoji/unamused.png">
            <img title=":sweat_smile:" class="emoji" src="/assets/img/emoji/sweat_smile.png">
            <img title=":sweat:" class="emoji" src="/assets/img/emoji/sweat.png">
            <img title=":weary:" class="emoji" src="/assets/img/emoji/weary.png">
            <img title=":pensive:" class="emoji" src="/assets/img/emoji/pensive.png">
            <img title=":disappointed:" class="emoji" src="/assets/img/emoji/disappointed.png">
            <img title=":confounded:" class="emoji" src="/assets/img/emoji/confounded.png">
            <img title=":fearful:" class="emoji" src="/assets/img/emoji/fearful.png">
            <img title=":cold_sweat:" class="emoji" src="/assets/img/emoji/cold_sweat.png">
            <img title=":persevere:" class="emoji" src="/assets/img/emoji/persevere.png">
            <img title=":cry:" class="emoji" src="/assets/img/emoji/cry.png">
            <img title=":sob:" class="emoji" src="/assets/img/emoji/sob.png">
            <img title=":joy:" class="emoji" src="/assets/img/emoji/joy.png">
            <img title=":astonished:" class="emoji" src="/assets/img/emoji/astonished.png">
            <img title=":scream:" class="emoji" src="/assets/img/emoji/scream.png">
            <img title=":neckbeard:" class="emoji" src="/assets/img/emoji/neckbeard.png">
            <img title=":tired_face:" class="emoji" src="/assets/img/emoji/tired_face.png">
            <img title=":angry:" class="emoji" src="/assets/img/emoji/angry.png">
            <img title=":rage:" class="emoji" src="/assets/img/emoji/rage.png">
            <img title=":triumph:" class="emoji" src="/assets/img/emoji/triumph.png">
            <img title=":sleepy:" class="emoji" src="/assets/img/emoji/sleepy.png">
            <img title=":yum:" class="emoji" src="/assets/img/emoji/yum.png">
            <img title=":mask:" class="emoji" src="/assets/img/emoji/mask.png">
            <img title=":sunglasses:" class="emoji" src="/assets/img/emoji/sunglasses.png">
            <img title=":dizzy_face:" class="emoji" src="/assets/img/emoji/dizzy_face.png">
            <img title=":imp:" class="emoji" src="/assets/img/emoji/imp.png">
            <img title=":smiling_imp:" class="emoji" src="/assets/img/emoji/smiling_imp.png">
            <img title=":neutral_face:" class="emoji" src="/assets/img/emoji/neutral_face.png">
            <img title=":no_mouth:" class="emoji" src="/assets/img/emoji/no_mouth.png">
            <img title=":innocent:" class="emoji" src="/assets/img/emoji/innocent.png">
            <img title=":alien:" class="emoji" src="/assets/img/emoji/alien.png">
            <img title=":yellow_heart:" class="emoji" src="/assets/img/emoji/yellow_heart.png">
            <img title=":blue_heart:" class="emoji" src="/assets/img/emoji/blue_heart.png">
            <img title=":purple_heart:" class="emoji" src="/assets/img/emoji/purple_heart.png">
            <img title=":heart:" class="emoji" src="/assets/img/emoji/heart.png">
            <img title=":green_heart:" class="emoji" src="/assets/img/emoji/green_heart.png">
            <img title=":broken_heart:" class="emoji" src="/assets/img/emoji/broken_heart.png">
            <img title=":heartbeat:" class="emoji" src="/assets/img/emoji/heartbeat.png">
            <img title=":heartpulse:" class="emoji" src="/assets/img/emoji/heartpulse.png">
            <img title=":two_hearts:" class="emoji" src="/assets/img/emoji/two_hearts.png">
            <img title=":revolving_hearts:" class="emoji" src="/assets/img/emoji/revolving_hearts.png">
            <img title=":cupid:" class="emoji" src="/assets/img/emoji/cupid.png">
            <img title=":sparkling_heart:" class="emoji" src="/assets/img/emoji/sparkling_heart.png">
            <img title=":sparkles:" class="emoji" src="/assets/img/emoji/sparkles.png">
            <img title=":star:" class="emoji" src="/assets/img/emoji/star.png">
            <img title=":star2:" class="emoji" src="/assets/img/emoji/star2.png">
            <img title=":dizzy:" class="emoji" src="/assets/img/emoji/dizzy.png">
            <img title=":boom:" class="emoji" src="/assets/img/emoji/boom.png">
            <img title=":collision:" class="emoji" src="/assets/img/emoji/collision.png">
            <img title=":anger:" class="emoji" src="/assets/img/emoji/anger.png">
            <img title=":exclamation:" class="emoji" src="/assets/img/emoji/exclamation.png">
            <img title=":question:" class="emoji" src="/assets/img/emoji/question.png">
            <img title=":grey_exclamation:" class="emoji" src="/assets/img/emoji/grey_exclamation.png">
            <img title=":grey_question:" class="emoji" src="/assets/img/emoji/grey_question.png">
            <img title=":zzz:" class="emoji" src="/assets/img/emoji/zzz.png">
            <img title=":dash:" class="emoji" src="/assets/img/emoji/dash.png">
            <img title=":sweat_drops:" class="emoji" src="/assets/img/emoji/sweat_drops.png">
            <img title=":notes:" class="emoji" src="/assets/img/emoji/notes.png">
            <img title=":musical_note:" class="emoji" src="/assets/img/emoji/musical_note.png">
            <img title=":fire:" class="emoji" src="/assets/img/emoji/fire.png">
            <img title=":hankey:" class="emoji" src="/assets/img/emoji/hankey.png">
            <img title=":poop:" class="emoji" src="/assets/img/emoji/poop.png">
            <img title=":shit:" class="emoji" src="/assets/img/emoji/shit.png">
            <img title=":thumbsup:" class="emoji" src="/assets/img/emoji/thumbsup.png">
            <img title=":thumbsup:" class="emoji" src="/assets/img/emoji/thumbsup.png">
            :-1:
            <img title=":thumbsdown:" class="emoji" src="/assets/img/emoji/thumbsdown.png">
            <img title=":ok_hand:" class="emoji" src="/assets/img/emoji/ok_hand.png">
            <img title=":punch:" class="emoji" src="/assets/img/emoji/punch.png">
            <img title=":facepunch:" class="emoji" src="/assets/img/emoji/facepunch.png">
            <img title=":fist:" class="emoji" src="/assets/img/emoji/fist.png">
            <img title=":v:" class="emoji" src="/assets/img/emoji/v.png">
            <img title=":wave:" class="emoji" src="/assets/img/emoji/wave.png">
            <img title=":hand:" class="emoji" src="/assets/img/emoji/hand.png">
            <img title=":open_hands:" class="emoji" src="/assets/img/emoji/open_hands.png">
            <img title=":point_up:" class="emoji" src="/assets/img/emoji/point_up.png">
            <img title=":point_down:" class="emoji" src="/assets/img/emoji/point_down.png">
            <img title=":point_left:" class="emoji" src="/assets/img/emoji/point_left.png">
            <img title=":point_right:" class="emoji" src="/assets/img/emoji/point_right.png">
            <img title=":raised_hands:" class="emoji" src="/assets/img/emoji/raised_hands.png">
            <img title=":pray:" class="emoji" src="/assets/img/emoji/pray.png">
            <img title=":point_up_2:" class="emoji" src="/assets/img/emoji/point_up_2.png">
            <img title=":clap:" class="emoji" src="/assets/img/emoji/clap.png">
            <img title=":muscle:" class="emoji" src="/assets/img/emoji/muscle.png">
            <img title=":metal:" class="emoji" src="/assets/img/emoji/metal.png">
            <img title=":walking:" class="emoji" src="/assets/img/emoji/walking.png">
            <img title=":runner:" class="emoji" src="/assets/img/emoji/runner.png">
            <img title=":running:" class="emoji" src="/assets/img/emoji/running.png">
            <img title=":couple:" class="emoji" src="/assets/img/emoji/couple.png">
            <img title=":family:" class="emoji" src="/assets/img/emoji/family.png">
            <img title=":two_men_holding_hands:" class="emoji" src="/assets/img/emoji/two_men_holding_hands.png">
            <img title=":two_women_holding_hands:" class="emoji" src="/assets/img/emoji/two_women_holding_hands.png">
            <img title=":dancer:" class="emoji" src="/assets/img/emoji/dancer.png">
            <img title=":dancers:" class="emoji" src="/assets/img/emoji/dancers.png">
            <img title=":ok_woman:" class="emoji" src="/assets/img/emoji/ok_woman.png">
            <img title=":no_good:" class="emoji" src="/assets/img/emoji/no_good.png">
            <img title=":information_desk_person:" class="emoji" src="/assets/img/emoji/information_desk_person.png">
            <img title=":raised_hand:" class="emoji" src="/assets/img/emoji/raised_hand.png">
            <img title=":bride_with_veil:" class="emoji" src="/assets/img/emoji/bride_with_veil.png">
            <img title=":person_with_pouting_face:" class="emoji" src="/assets/img/emoji/person_with_pouting_face.png">
            <img title=":person_frowning:" class="emoji" src="/assets/img/emoji/person_frowning.png">
            <img title=":bow:" class="emoji" src="/assets/img/emoji/bow.png">
            <img title=":couplekiss:" class="emoji" src="/assets/img/emoji/couplekiss.png">
            <img title=":couple_with_heart:" class="emoji" src="/assets/img/emoji/couple_with_heart.png">
            <img title=":massage:" class="emoji" src="/assets/img/emoji/massage.png">
            <img title=":haircut:" class="emoji" src="/assets/img/emoji/haircut.png">
            <img title=":nail_care:" class="emoji" src="/assets/img/emoji/nail_care.png">
            <img title=":boy:" class="emoji" src="/assets/img/emoji/boy.png">
            <img title=":girl:" class="emoji" src="/assets/img/emoji/girl.png">
            <img title=":woman:" class="emoji" src="/assets/img/emoji/woman.png">
            <img title=":man:" class="emoji" src="/assets/img/emoji/man.png">
            <img title=":baby:" class="emoji" src="/assets/img/emoji/baby.png">
            <img title=":older_woman:" class="emoji" src="/assets/img/emoji/older_woman.png">
            <img title=":older_man:" class="emoji" src="/assets/img/emoji/older_man.png">
            <img title=":person_with_blond_hair:" class="emoji" src="/assets/img/emoji/person_with_blond_hair.png">
            <img title=":man_with_gua_pi_mao:" class="emoji" src="/assets/img/emoji/man_with_gua_pi_mao.png">
            <img title=":man_with_turban:" class="emoji" src="/assets/img/emoji/man_with_turban.png">
            <img title=":construction_worker:" class="emoji" src="/assets/img/emoji/construction_worker.png">
            <img title=":cop:" class="emoji" src="/assets/img/emoji/cop.png">
            <img title=":angel:" class="emoji" src="/assets/img/emoji/angel.png">
            <img title=":princess:" class="emoji" src="/assets/img/emoji/princess.png">
            <img title=":smiley_cat:" class="emoji" src="/assets/img/emoji/smiley_cat.png">
            <img title=":smile_cat:" class="emoji" src="/assets/img/emoji/smile_cat.png">
            <img title=":heart_eyes_cat:" class="emoji" src="/assets/img/emoji/heart_eyes_cat.png">
            <img title=":kissing_cat:" class="emoji" src="/assets/img/emoji/kissing_cat.png">
            <img title=":smirk_cat:" class="emoji" src="/assets/img/emoji/smirk_cat.png">
            <img title=":scream_cat:" class="emoji" src="/assets/img/emoji/scream_cat.png">
            <img title=":crying_cat_face:" class="emoji" src="/assets/img/emoji/crying_cat_face.png">
            <img title=":joy_cat:" class="emoji" src="/assets/img/emoji/joy_cat.png">
            <img title=":pouting_cat:" class="emoji" src="/assets/img/emoji/pouting_cat.png">
            <img title=":japanese_ogre:" class="emoji" src="/assets/img/emoji/japanese_ogre.png">
            <img title=":japanese_goblin:" class="emoji" src="/assets/img/emoji/japanese_goblin.png">
            <img title=":see_no_evil:" class="emoji" src="/assets/img/emoji/see_no_evil.png">
            <img title=":hear_no_evil:" class="emoji" src="/assets/img/emoji/hear_no_evil.png">
            <img title=":speak_no_evil:" class="emoji" src="/assets/img/emoji/speak_no_evil.png">
            <img title=":guardsman:" class="emoji" src="/assets/img/emoji/guardsman.png">
            <img title=":skull:" class="emoji" src="/assets/img/emoji/skull.png">
            <img title=":feet:" class="emoji" src="/assets/img/emoji/feet.png">
            <img title=":lips:" class="emoji" src="/assets/img/emoji/lips.png">
            <img title=":kiss:" class="emoji" src="/assets/img/emoji/kiss.png">
            <img title=":droplet:" class="emoji" src="/assets/img/emoji/droplet.png">
            <img title=":ear:" class="emoji" src="/assets/img/emoji/ear.png">
            <img title=":eyes:" class="emoji" src="/assets/img/emoji/eyes.png">
            <img title=":nose:" class="emoji" src="/assets/img/emoji/nose.png">
            <img title=":tongue:" class="emoji" src="/assets/img/emoji/tongue.png">
            <img title=":love_letter:" class="emoji" src="/assets/img/emoji/love_letter.png">
            <img title=":bust_in_silhouette:" class="emoji" src="/assets/img/emoji/bust_in_silhouette.png">
            <img title=":busts_in_silhouette:" class="emoji" src="/assets/img/emoji/busts_in_silhouette.png">
            <img title=":speech_balloon:" class="emoji" src="/assets/img/emoji/speech_balloon.png">
            <img title=":thought_balloon:" class="emoji" src="/assets/img/emoji/thought_balloon.png">
            <img title=":feelsgood:" class="emoji" src="/assets/img/emoji/feelsgood.png">
            <img title=":finnadie:" class="emoji" src="/assets/img/emoji/finnadie.png">
            <img title=":goberserk:" class="emoji" src="/assets/img/emoji/goberserk.png">
            <img title=":godmode:" class="emoji" src="/assets/img/emoji/godmode.png">
            <img title=":hurtrealbad:" class="emoji" src="/assets/img/emoji/hurtrealbad.png">
            <img title=":rage1:" class="emoji" src="/assets/img/emoji/rage1.png">
            <img title=":rage2:" class="emoji" src="/assets/img/emoji/rage2.png">
            <img title=":rage3:" class="emoji" src="/assets/img/emoji/rage3.png">
            <img title=":rage4:" class="emoji" src="/assets/img/emoji/rage4.png">
            <img title=":suspect:" class="emoji" src="/assets/img/emoji/suspect.png">
            <img title=":trollface:" class="emoji" src="/assets/img/emoji/trollface.png">
      </p>
      <h2>Nature</h2>
      <p>
            <img title=":sunny:" class="emoji" src="/assets/img/emoji/sunny.png">
            <img title=":umbrella:" class="emoji" src="/assets/img/emoji/umbrella.png">
            <img title=":cloud:" class="emoji" src="/assets/img/emoji/cloud.png">
            <img title=":snowflake:" class="emoji" src="/assets/img/emoji/snowflake.png">
            <img title=":snowman:" class="emoji" src="/assets/img/emoji/snowman.png">
            <img title=":zap:" class="emoji" src="/assets/img/emoji/zap.png">
            <img title=":cyclone:" class="emoji" src="/assets/img/emoji/cyclone.png">
            <img title=":foggy:" class="emoji" src="/assets/img/emoji/foggy.png">
            <img title=":ocean:" class="emoji" src="/assets/img/emoji/ocean.png">
            <img title=":cat:" class="emoji" src="/assets/img/emoji/cat.png">
            <img title=":dog:" class="emoji" src="/assets/img/emoji/dog.png">
            <img title=":mouse:" class="emoji" src="/assets/img/emoji/mouse.png">
            <img title=":hamster:" class="emoji" src="/assets/img/emoji/hamster.png">
            <img title=":rabbit:" class="emoji" src="/assets/img/emoji/rabbit.png">
            <img title=":wolf:" class="emoji" src="/assets/img/emoji/wolf.png">
            <img title=":frog:" class="emoji" src="/assets/img/emoji/frog.png">
            <img title=":tiger:" class="emoji" src="/assets/img/emoji/tiger.png">
            <img title=":koala:" class="emoji" src="/assets/img/emoji/koala.png">
            <img title=":bear:" class="emoji" src="/assets/img/emoji/bear.png">
            <img title=":pig:" class="emoji" src="/assets/img/emoji/pig.png">
            <img title=":pig_nose:" class="emoji" src="/assets/img/emoji/pig_nose.png">
            <img title=":cow:" class="emoji" src="/assets/img/emoji/cow.png">
            <img title=":boar:" class="emoji" src="/assets/img/emoji/boar.png">
            <img title=":monkey_face:" class="emoji" src="/assets/img/emoji/monkey_face.png">
            <img title=":monkey:" class="emoji" src="/assets/img/emoji/monkey.png">
            <img title=":horse:" class="emoji" src="/assets/img/emoji/horse.png">
            <img title=":racehorse:" class="emoji" src="/assets/img/emoji/racehorse.png">
            <img title=":camel:" class="emoji" src="/assets/img/emoji/camel.png">
            <img title=":sheep:" class="emoji" src="/assets/img/emoji/sheep.png">
            <img title=":elephant:" class="emoji" src="/assets/img/emoji/elephant.png">
            <img title=":panda_face:" class="emoji" src="/assets/img/emoji/panda_face.png">
            <img title=":snake:" class="emoji" src="/assets/img/emoji/snake.png">
            <img title=":bird:" class="emoji" src="/assets/img/emoji/bird.png">
            <img title=":baby_chick:" class="emoji" src="/assets/img/emoji/baby_chick.png">
            <img title=":hatched_chick:" class="emoji" src="/assets/img/emoji/hatched_chick.png">
            <img title=":hatching_chick:" class="emoji" src="/assets/img/emoji/hatching_chick.png">
            <img title=":chicken:" class="emoji" src="/assets/img/emoji/chicken.png">
            <img title=":penguin:" class="emoji" src="/assets/img/emoji/penguin.png">
            <img title=":turtle:" class="emoji" src="/assets/img/emoji/turtle.png">
            <img title=":bug:" class="emoji" src="/assets/img/emoji/bug.png">
            <img title=":honeybee:" class="emoji" src="/assets/img/emoji/honeybee.png">
            <img title=":ant:" class="emoji" src="/assets/img/emoji/ant.png">
            <img title=":beetle:" class="emoji" src="/assets/img/emoji/beetle.png">
            <img title=":snail:" class="emoji" src="/assets/img/emoji/snail.png">
            <img title=":octopus:" class="emoji" src="/assets/img/emoji/octopus.png">
            <img title=":tropical_fish:" class="emoji" src="/assets/img/emoji/tropical_fish.png">
            <img title=":fish:" class="emoji" src="/assets/img/emoji/fish.png">
            <img title=":whale:" class="emoji" src="/assets/img/emoji/whale.png">
            <img title=":whale2:" class="emoji" src="/assets/img/emoji/whale2.png">
            <img title=":dolphin:" class="emoji" src="/assets/img/emoji/dolphin.png">
            <img title=":cow2:" class="emoji" src="/assets/img/emoji/cow2.png">
            <img title=":ram:" class="emoji" src="/assets/img/emoji/ram.png">
            <img title=":rat:" class="emoji" src="/assets/img/emoji/rat.png">
            <img title=":water_buffalo:" class="emoji" src="/assets/img/emoji/water_buffalo.png">
            <img title=":tiger2:" class="emoji" src="/assets/img/emoji/tiger2.png">
            <img title=":rabbit2:" class="emoji" src="/assets/img/emoji/rabbit2.png">
            <img title=":dragon:" class="emoji" src="/assets/img/emoji/dragon.png">
            <img title=":goat:" class="emoji" src="/assets/img/emoji/goat.png">
            <img title=":rooster:" class="emoji" src="/assets/img/emoji/rooster.png">
            <img title=":dog2:" class="emoji" src="/assets/img/emoji/dog2.png">
            <img title=":pig2:" class="emoji" src="/assets/img/emoji/pig2.png">
            <img title=":mouse2:" class="emoji" src="/assets/img/emoji/mouse2.png">
            <img title=":ox:" class="emoji" src="/assets/img/emoji/ox.png">
            <img title=":dragon_face:" class="emoji" src="/assets/img/emoji/dragon_face.png">
            <img title=":blowfish:" class="emoji" src="/assets/img/emoji/blowfish.png">
            <img title=":crocodile:" class="emoji" src="/assets/img/emoji/crocodile.png">
            <img title=":dromedary_camel:" class="emoji" src="/assets/img/emoji/dromedary_camel.png">
            <img title=":leopard:" class="emoji" src="/assets/img/emoji/leopard.png">
            <img title=":cat2:" class="emoji" src="/assets/img/emoji/cat2.png">
            <img title=":poodle:" class="emoji" src="/assets/img/emoji/poodle.png">
            <img title=":paw_prints:" class="emoji" src="/assets/img/emoji/paw_prints.png">
            <img title=":bouquet:" class="emoji" src="/assets/img/emoji/bouquet.png">
            <img title=":cherry_blossom:" class="emoji" src="/assets/img/emoji/cherry_blossom.png">
            <img title=":tulip:" class="emoji" src="/assets/img/emoji/tulip.png">
            <img title=":four_leaf_clover:" class="emoji" src="/assets/img/emoji/four_leaf_clover.png">
            <img title=":rose:" class="emoji" src="/assets/img/emoji/rose.png">
            <img title=":sunflower:" class="emoji" src="/assets/img/emoji/sunflower.png">
            <img title=":hibiscus:" class="emoji" src="/assets/img/emoji/hibiscus.png">
            <img title=":maple_leaf:" class="emoji" src="/assets/img/emoji/maple_leaf.png">
            <img title=":leaves:" class="emoji" src="/assets/img/emoji/leaves.png">
            <img title=":fallen_leaf:" class="emoji" src="/assets/img/emoji/fallen_leaf.png">
            <img title=":herb:" class="emoji" src="/assets/img/emoji/herb.png">
            <img title=":mushroom:" class="emoji" src="/assets/img/emoji/mushroom.png">
            <img title=":cactus:" class="emoji" src="/assets/img/emoji/cactus.png">
            <img title=":palm_tree:" class="emoji" src="/assets/img/emoji/palm_tree.png">
            <img title=":evergreen_tree:" class="emoji" src="/assets/img/emoji/evergreen_tree.png">
            <img title=":deciduous_tree:" class="emoji" src="/assets/img/emoji/deciduous_tree.png">
            <img title=":chestnut:" class="emoji" src="/assets/img/emoji/chestnut.png">
            <img title=":seedling:" class="emoji" src="/assets/img/emoji/seedling.png">
            <img title=":blossom:" class="emoji" src="/assets/img/emoji/blossom.png">
            <img title=":ear_of_rice:" class="emoji" src="/assets/img/emoji/ear_of_rice.png">
            <img title=":shell:" class="emoji" src="/assets/img/emoji/shell.png">
            <img title=":globe_with_meridians:" class="emoji" src="/assets/img/emoji/globe_with_meridians.png">
            <img title=":sun_with_face:" class="emoji" src="/assets/img/emoji/sun_with_face.png">
            <img title=":full_moon_with_face:" class="emoji" src="/assets/img/emoji/full_moon_with_face.png">
            <img title=":new_moon_with_face:" class="emoji" src="/assets/img/emoji/new_moon_with_face.png">
            <img title=":new_moon:" class="emoji" src="/assets/img/emoji/new_moon.png">
            <img title=":waxing_crescent_moon:" class="emoji" src="/assets/img/emoji/waxing_crescent_moon.png">
            <img title=":first_quarter_moon:" class="emoji" src="/assets/img/emoji/first_quarter_moon.png">
            <img title=":waxing_gibbous_moon:" class="emoji" src="/assets/img/emoji/waxing_gibbous_moon.png">
            <img title=":full_moon:" class="emoji" src="/assets/img/emoji/full_moon.png">
            <img title=":waning_gibbous_moon:" class="emoji" src="/assets/img/emoji/waning_gibbous_moon.png">
            <img title=":last_quarter_moon:" class="emoji" src="/assets/img/emoji/last_quarter_moon.png">
            <img title=":waning_crescent_moon:" class="emoji" src="/assets/img/emoji/waning_crescent_moon.png">
            <img title=":last_quarter_moon_with_face:" class="emoji" src="/assets/img/emoji/last_quarter_moon_with_face.png">
            <img title=":first_quarter_moon_with_face:" class="emoji" src="/assets/img/emoji/first_quarter_moon_with_face.png">
            <img title=":moon:" class="emoji" src="/assets/img/emoji/moon.png">
            <img title=":earth_africa:" class="emoji" src="/assets/img/emoji/earth_africa.png">
            <img title=":earth_americas:" class="emoji" src="/assets/img/emoji/earth_americas.png">
            <img title=":earth_asia:" class="emoji" src="/assets/img/emoji/earth_asia.png">
            <img title=":volcano:" class="emoji" src="/assets/img/emoji/volcano.png">
            <img title=":milky_way:" class="emoji" src="/assets/img/emoji/milky_way.png">
            <img title=":partly_sunny:" class="emoji" src="/assets/img/emoji/partly_sunny.png">
            <img title=":octocat:" class="emoji" src="/assets/img/emoji/octocat.png">
            <img title=":squirrel:" class="emoji" src="/assets/img/emoji/squirrel.png">
      </p>
      <h2>Objects</h2>
      <p>
            <img title=":bamboo:" class="emoji" src="/assets/img/emoji/bamboo.png">
            <img title=":gift_heart:" class="emoji" src="/assets/img/emoji/gift_heart.png">
            <img title=":dolls:" class="emoji" src="/assets/img/emoji/dolls.png">
            <img title=":school_satchel:" class="emoji" src="/assets/img/emoji/school_satchel.png">
            <img title=":mortar_board:" class="emoji" src="/assets/img/emoji/mortar_board.png">
            <img title=":flags:" class="emoji" src="/assets/img/emoji/flags.png">
            <img title=":fireworks:" class="emoji" src="/assets/img/emoji/fireworks.png">
            <img title=":sparkler:" class="emoji" src="/assets/img/emoji/sparkler.png">
            <img title=":wind_chime:" class="emoji" src="/assets/img/emoji/wind_chime.png">
            <img title=":rice_scene:" class="emoji" src="/assets/img/emoji/rice_scene.png">
            <img title=":jack_o_lantern:" class="emoji" src="/assets/img/emoji/jack_o_lantern.png">
            <img title=":ghost:" class="emoji" src="/assets/img/emoji/ghost.png">
            <img title=":santa:" class="emoji" src="/assets/img/emoji/santa.png">
            <img title=":christmas_tree:" class="emoji" src="/assets/img/emoji/christmas_tree.png">
            <img title=":gift:" class="emoji" src="/assets/img/emoji/gift.png">
            <img title=":bell:" class="emoji" src="/assets/img/emoji/bell.png">
            <img title=":no_bell:" class="emoji" src="/assets/img/emoji/no_bell.png">
            <img title=":tanabata_tree:" class="emoji" src="/assets/img/emoji/tanabata_tree.png">
            <img title=":tada:" class="emoji" src="/assets/img/emoji/tada.png">
            <img title=":confetti_ball:" class="emoji" src="/assets/img/emoji/confetti_ball.png">
            <img title=":balloon:" class="emoji" src="/assets/img/emoji/balloon.png">
            <img title=":crystal_ball:" class="emoji" src="/assets/img/emoji/crystal_ball.png">
            <img title=":cd:" class="emoji" src="/assets/img/emoji/cd.png">
            <img title=":dvd:" class="emoji" src="/assets/img/emoji/dvd.png">
            <img title=":floppy_disk:" class="emoji" src="/assets/img/emoji/floppy_disk.png">
            <img title=":camera:" class="emoji" src="/assets/img/emoji/camera.png">
            <img title=":video_camera:" class="emoji" src="/assets/img/emoji/video_camera.png">
            <img title=":movie_camera:" class="emoji" src="/assets/img/emoji/movie_camera.png">
            <img title=":computer:" class="emoji" src="/assets/img/emoji/computer.png">
            <img title=":tv:" class="emoji" src="/assets/img/emoji/tv.png">
            <img title=":iphone:" class="emoji" src="/assets/img/emoji/iphone.png">
            <img title=":phone:" class="emoji" src="/assets/img/emoji/phone.png">
            <img title=":telephone:" class="emoji" src="/assets/img/emoji/telephone.png">
            <img title=":telephone_receiver:" class="emoji" src="/assets/img/emoji/telephone_receiver.png">
            <img title=":pager:" class="emoji" src="/assets/img/emoji/pager.png">
            <img title=":fax:" class="emoji" src="/assets/img/emoji/fax.png">
            <img title=":minidisc:" class="emoji" src="/assets/img/emoji/minidisc.png">
            <img title=":vhs:" class="emoji" src="/assets/img/emoji/vhs.png">
            <img title=":sound:" class="emoji" src="/assets/img/emoji/sound.png">
            <img title=":speaker:" class="emoji" src="/assets/img/emoji/speaker.png">
            <img title=":mute:" class="emoji" src="/assets/img/emoji/mute.png">
            <img title=":loudspeaker:" class="emoji" src="/assets/img/emoji/loudspeaker.png">
            <img title=":mega:" class="emoji" src="/assets/img/emoji/mega.png">
            <img title=":hourglass:" class="emoji" src="/assets/img/emoji/hourglass.png">
            <img title=":hourglass_flowing_sand:" class="emoji" src="/assets/img/emoji/hourglass_flowing_sand.png">
            <img title=":alarm_clock:" class="emoji" src="/assets/img/emoji/alarm_clock.png">
            <img title=":watch:" class="emoji" src="/assets/img/emoji/watch.png">
            <img title=":radio:" class="emoji" src="/assets/img/emoji/radio.png">
            <img title=":satellite:" class="emoji" src="/assets/img/emoji/satellite.png">
            <img title=":loop:" class="emoji" src="/assets/img/emoji/loop.png">
            <img title=":mag:" class="emoji" src="/assets/img/emoji/mag.png">
            <img title=":mag_right:" class="emoji" src="/assets/img/emoji/mag_right.png">
            <img title=":unlock:" class="emoji" src="/assets/img/emoji/unlock.png">
            <img title=":lock:" class="emoji" src="/assets/img/emoji/lock.png">
            <img title=":lock_with_ink_pen:" class="emoji" src="/assets/img/emoji/lock_with_ink_pen.png">
            <img title=":closed_lock_with_key:" class="emoji" src="/assets/img/emoji/closed_lock_with_key.png">
            <img title=":key:" class="emoji" src="/assets/img/emoji/key.png">
            <img title=":bulb:" class="emoji" src="/assets/img/emoji/bulb.png">
            <img title=":flashlight:" class="emoji" src="/assets/img/emoji/flashlight.png">
            <img title=":high_brightness:" class="emoji" src="/assets/img/emoji/high_brightness.png">
            <img title=":low_brightness:" class="emoji" src="/assets/img/emoji/low_brightness.png">
            <img title=":electric_plug:" class="emoji" src="/assets/img/emoji/electric_plug.png">
            <img title=":battery:" class="emoji" src="/assets/img/emoji/battery.png">
            <img title=":calling:" class="emoji" src="/assets/img/emoji/calling.png">
            <img title=":email:" class="emoji" src="/assets/img/emoji/email.png">
            <img title=":mailbox:" class="emoji" src="/assets/img/emoji/mailbox.png">
            <img title=":postbox:" class="emoji" src="/assets/img/emoji/postbox.png">
            <img title=":bath:" class="emoji" src="/assets/img/emoji/bath.png">
            <img title=":bathtub:" class="emoji" src="/assets/img/emoji/bathtub.png">
            <img title=":shower:" class="emoji" src="/assets/img/emoji/shower.png">
            <img title=":toilet:" class="emoji" src="/assets/img/emoji/toilet.png">
            <img title=":wrench:" class="emoji" src="/assets/img/emoji/wrench.png">
            <img title=":nut_and_bolt:" class="emoji" src="/assets/img/emoji/nut_and_bolt.png">
            <img title=":hammer:" class="emoji" src="/assets/img/emoji/hammer.png">
            <img title=":seat:" class="emoji" src="/assets/img/emoji/seat.png">
            <img title=":moneybag:" class="emoji" src="/assets/img/emoji/moneybag.png">
            <img title=":yen:" class="emoji" src="/assets/img/emoji/yen.png">
            <img title=":dollar:" class="emoji" src="/assets/img/emoji/dollar.png">
            <img title=":pound:" class="emoji" src="/assets/img/emoji/pound.png">
            <img title=":euro:" class="emoji" src="/assets/img/emoji/euro.png">
            <img title=":credit_card:" class="emoji" src="/assets/img/emoji/credit_card.png">
            <img title=":money_with_wings:" class="emoji" src="/assets/img/emoji/money_with_wings.png">
            <img title=":e-mail:" class="emoji" src="/assets/img/emoji/e-mail.png">
            <img title=":inbox_tray:" class="emoji" src="/assets/img/emoji/inbox_tray.png">
            <img title=":outbox_tray:" class="emoji" src="/assets/img/emoji/outbox_tray.png">
            <img title=":envelope:" class="emoji" src="/assets/img/emoji/envelope.png">
            <img title=":incoming_envelope:" class="emoji" src="/assets/img/emoji/incoming_envelope.png">
            <img title=":postal_horn:" class="emoji" src="/assets/img/emoji/postal_horn.png">
            <img title=":mailbox_closed:" class="emoji" src="/assets/img/emoji/mailbox_closed.png">
            <img title=":mailbox_with_mail:" class="emoji" src="/assets/img/emoji/mailbox_with_mail.png">
            <img title=":mailbox_with_no_mail:" class="emoji" src="/assets/img/emoji/mailbox_with_no_mail.png">
            <img title=":door:" class="emoji" src="/assets/img/emoji/door.png">
            <img title=":smoking:" class="emoji" src="/assets/img/emoji/smoking.png">
            <img title=":bomb:" class="emoji" src="/assets/img/emoji/bomb.png">
            <img title=":gun:" class="emoji" src="/assets/img/emoji/gun.png">
            <img title=":hocho:" class="emoji" src="/assets/img/emoji/hocho.png">
            <img title=":pill:" class="emoji" src="/assets/img/emoji/pill.png">
            <img title=":syringe:" class="emoji" src="/assets/img/emoji/syringe.png">
            <img title=":page_facing_up:" class="emoji" src="/assets/img/emoji/page_facing_up.png">
            <img title=":page_with_curl:" class="emoji" src="/assets/img/emoji/page_with_curl.png">
            <img title=":bookmark_tabs:" class="emoji" src="/assets/img/emoji/bookmark_tabs.png">
            <img title=":bar_chart:" class="emoji" src="/assets/img/emoji/bar_chart.png">
            <img title=":chart_with_upwards_trend:" class="emoji" src="/assets/img/emoji/chart_with_upwards_trend.png">
            <img title=":chart_with_downwards_trend:" class="emoji" src="/assets/img/emoji/chart_with_downwards_trend.png">
            <img title=":scroll:" class="emoji" src="/assets/img/emoji/scroll.png">
            <img title=":clipboard:" class="emoji" src="/assets/img/emoji/clipboard.png">
            <img title=":calendar:" class="emoji" src="/assets/img/emoji/calendar.png">
            <img title=":date:" class="emoji" src="/assets/img/emoji/date.png">
            <img title=":card_index:" class="emoji" src="/assets/img/emoji/card_index.png">
            <img title=":file_folder:" class="emoji" src="/assets/img/emoji/file_folder.png">
            <img title=":open_file_folder:" class="emoji" src="/assets/img/emoji/open_file_folder.png">
            <img title=":scissors:" class="emoji" src="/assets/img/emoji/scissors.png">
            <img title=":pushpin:" class="emoji" src="/assets/img/emoji/pushpin.png">
            <img title=":paperclip:" class="emoji" src="/assets/img/emoji/paperclip.png">
            <img title=":black_nib:" class="emoji" src="/assets/img/emoji/black_nib.png">
            <img title=":pencil2:" class="emoji" src="/assets/img/emoji/pencil2.png">
            <img title=":straight_ruler:" class="emoji" src="/assets/img/emoji/straight_ruler.png">
            <img title=":triangular_ruler:" class="emoji" src="/assets/img/emoji/triangular_ruler.png">
            <img title=":closed_book:" class="emoji" src="/assets/img/emoji/closed_book.png">
            <img title=":green_book:" class="emoji" src="/assets/img/emoji/green_book.png">
            <img title=":blue_book:" class="emoji" src="/assets/img/emoji/blue_book.png">
            <img title=":orange_book:" class="emoji" src="/assets/img/emoji/orange_book.png">
            <img title=":notebook:" class="emoji" src="/assets/img/emoji/notebook.png">
            <img title=":notebook_with_decorative_cover:" class="emoji" src="/assets/img/emoji/notebook_with_decorative_cover.png">
            <img title=":ledger:" class="emoji" src="/assets/img/emoji/ledger.png">
            <img title=":books:" class="emoji" src="/assets/img/emoji/books.png">
            <img title=":bookmark:" class="emoji" src="/assets/img/emoji/bookmark.png">
            <img title=":name_badge:" class="emoji" src="/assets/img/emoji/name_badge.png">
            <img title=":microscope:" class="emoji" src="/assets/img/emoji/microscope.png">
            <img title=":telescope:" class="emoji" src="/assets/img/emoji/telescope.png">
            <img title=":newspaper:" class="emoji" src="/assets/img/emoji/newspaper.png">
            <img title=":football:" class="emoji" src="/assets/img/emoji/football.png">
            <img title=":basketball:" class="emoji" src="/assets/img/emoji/basketball.png">
            <img title=":soccer:" class="emoji" src="/assets/img/emoji/soccer.png">
            <img title=":baseball:" class="emoji" src="/assets/img/emoji/baseball.png">
            <img title=":tennis:" class="emoji" src="/assets/img/emoji/tennis.png">
            <img title=":8ball:" class="emoji" src="/assets/img/emoji/8ball.png">
            <img title=":rugby_football:" class="emoji" src="/assets/img/emoji/rugby_football.png">
            <img title=":bowling:" class="emoji" src="/assets/img/emoji/bowling.png">
            <img title=":golf:" class="emoji" src="/assets/img/emoji/golf.png">
            <img title=":mountain_bicyclist:" class="emoji" src="/assets/img/emoji/mountain_bicyclist.png">
            <img title=":bicyclist:" class="emoji" src="/assets/img/emoji/bicyclist.png">
            <img title=":horse_racing:" class="emoji" src="/assets/img/emoji/horse_racing.png">
            <img title=":snowboarder:" class="emoji" src="/assets/img/emoji/snowboarder.png">
            <img title=":swimmer:" class="emoji" src="/assets/img/emoji/swimmer.png">
            <img title=":surfer:" class="emoji" src="/assets/img/emoji/surfer.png">
            <img title=":ski:" class="emoji" src="/assets/img/emoji/ski.png">
            <img title=":spades:" class="emoji" src="/assets/img/emoji/spades.png">
            <img title=":hearts:" class="emoji" src="/assets/img/emoji/hearts.png">
            <img title=":clubs:" class="emoji" src="/assets/img/emoji/clubs.png">
            <img title=":diamonds:" class="emoji" src="/assets/img/emoji/diamonds.png">
            <img title=":gem:" class="emoji" src="/assets/img/emoji/gem.png">
            <img title=":ring:" class="emoji" src="/assets/img/emoji/ring.png">
            <img title=":trophy:" class="emoji" src="/assets/img/emoji/trophy.png">
            <img title=":musical_score:" class="emoji" src="/assets/img/emoji/musical_score.png">
            <img title=":musical_keyboard:" class="emoji" src="/assets/img/emoji/musical_keyboard.png">
            <img title=":violin:" class="emoji" src="/assets/img/emoji/violin.png">
            <img title=":space_invader:" class="emoji" src="/assets/img/emoji/space_invader.png">
            <img title=":video_game:" class="emoji" src="/assets/img/emoji/video_game.png">
            <img title=":black_joker:" class="emoji" src="/assets/img/emoji/black_joker.png">
            <img title=":flower_playing_cards:" class="emoji" src="/assets/img/emoji/flower_playing_cards.png">
            <img title=":game_die:" class="emoji" src="/assets/img/emoji/game_die.png">
            <img title=":dart:" class="emoji" src="/assets/img/emoji/dart.png">
            <img title=":mahjong:" class="emoji" src="/assets/img/emoji/mahjong.png">
            <img title=":clapper:" class="emoji" src="/assets/img/emoji/clapper.png">
            <img title=":memo:" class="emoji" src="/assets/img/emoji/memo.png">
            <img title=":pencil:" class="emoji" src="/assets/img/emoji/pencil.png">
            <img title=":book:" class="emoji" src="/assets/img/emoji/book.png">
            <img title=":art:" class="emoji" src="/assets/img/emoji/art.png">
            <img title=":microphone:" class="emoji" src="/assets/img/emoji/microphone.png">
            <img title=":headphones:" class="emoji" src="/assets/img/emoji/headphones.png">
            <img title=":trumpet:" class="emoji" src="/assets/img/emoji/trumpet.png">
            <img title=":saxophone:" class="emoji" src="/assets/img/emoji/saxophone.png">
            <img title=":guitar:" class="emoji" src="/assets/img/emoji/guitar.png">
            <img title=":shoe:" class="emoji" src="/assets/img/emoji/shoe.png">
            <img title=":sandal:" class="emoji" src="/assets/img/emoji/sandal.png">
            <img title=":high_heel:" class="emoji" src="/assets/img/emoji/high_heel.png">
            <img title=":lipstick:" class="emoji" src="/assets/img/emoji/lipstick.png">
            <img title=":boot:" class="emoji" src="/assets/img/emoji/boot.png">
            <img title=":shirt:" class="emoji" src="/assets/img/emoji/shirt.png">
            <img title=":tshirt:" class="emoji" src="/assets/img/emoji/tshirt.png">
            <img title=":necktie:" class="emoji" src="/assets/img/emoji/necktie.png">
            <img title=":womans_clothes:" class="emoji" src="/assets/img/emoji/womans_clothes.png">
            <img title=":dress:" class="emoji" src="/assets/img/emoji/dress.png">
            <img title=":running_shirt_with_sash:" class="emoji" src="/assets/img/emoji/running_shirt_with_sash.png">
            <img title=":jeans:" class="emoji" src="/assets/img/emoji/jeans.png">
            <img title=":kimono:" class="emoji" src="/assets/img/emoji/kimono.png">
            <img title=":bikini:" class="emoji" src="/assets/img/emoji/bikini.png">
            <img title=":ribbon:" class="emoji" src="/assets/img/emoji/ribbon.png">
            <img title=":tophat:" class="emoji" src="/assets/img/emoji/tophat.png">
            <img title=":crown:" class="emoji" src="/assets/img/emoji/crown.png">
            <img title=":womans_hat:" class="emoji" src="/assets/img/emoji/womans_hat.png">
            <img title=":mans_shoe:" class="emoji" src="/assets/img/emoji/mans_shoe.png">
            <img title=":closed_umbrella:" class="emoji" src="/assets/img/emoji/closed_umbrella.png">
            <img title=":briefcase:" class="emoji" src="/assets/img/emoji/briefcase.png">
            <img title=":handbag:" class="emoji" src="/assets/img/emoji/handbag.png">
            <img title=":pouch:" class="emoji" src="/assets/img/emoji/pouch.png">
            <img title=":purse:" class="emoji" src="/assets/img/emoji/purse.png">
            <img title=":eyeglasses:" class="emoji" src="/assets/img/emoji/eyeglasses.png">
            <img title=":fishing_pole_and_fish:" class="emoji" src="/assets/img/emoji/fishing_pole_and_fish.png">
            <img title=":coffee:" class="emoji" src="/assets/img/emoji/coffee.png">
            <img title=":tea:" class="emoji" src="/assets/img/emoji/tea.png">
            <img title=":sake:" class="emoji" src="/assets/img/emoji/sake.png">
            <img title=":baby_bottle:" class="emoji" src="/assets/img/emoji/baby_bottle.png">
            <img title=":beer:" class="emoji" src="/assets/img/emoji/beer.png">
            <img title=":beers:" class="emoji" src="/assets/img/emoji/beers.png">
            <img title=":cocktail:" class="emoji" src="/assets/img/emoji/cocktail.png">
            <img title=":tropical_drink:" class="emoji" src="/assets/img/emoji/tropical_drink.png">
            <img title=":wine_glass:" class="emoji" src="/assets/img/emoji/wine_glass.png">
            <img title=":fork_and_knife:" class="emoji" src="/assets/img/emoji/fork_and_knife.png">
            <img title=":pizza:" class="emoji" src="/assets/img/emoji/pizza.png">
            <img title=":hamburger:" class="emoji" src="/assets/img/emoji/hamburger.png">
            <img title=":fries:" class="emoji" src="/assets/img/emoji/fries.png">
            <img title=":poultry_leg:" class="emoji" src="/assets/img/emoji/poultry_leg.png">
            <img title=":meat_on_bone:" class="emoji" src="/assets/img/emoji/meat_on_bone.png">
            <img title=":spaghetti:" class="emoji" src="/assets/img/emoji/spaghetti.png">
            <img title=":curry:" class="emoji" src="/assets/img/emoji/curry.png">
            <img title=":fried_shrimp:" class="emoji" src="/assets/img/emoji/fried_shrimp.png">
            <img title=":bento:" class="emoji" src="/assets/img/emoji/bento.png">
            <img title=":sushi:" class="emoji" src="/assets/img/emoji/sushi.png">
            <img title=":fish_cake:" class="emoji" src="/assets/img/emoji/fish_cake.png">
            <img title=":rice_ball:" class="emoji" src="/assets/img/emoji/rice_ball.png">
            <img title=":rice_cracker:" class="emoji" src="/assets/img/emoji/rice_cracker.png">
            <img title=":rice:" class="emoji" src="/assets/img/emoji/rice.png">
            <img title=":ramen:" class="emoji" src="/assets/img/emoji/ramen.png">
            <img title=":stew:" class="emoji" src="/assets/img/emoji/stew.png">
            <img title=":oden:" class="emoji" src="/assets/img/emoji/oden.png">
            <img title=":dango:" class="emoji" src="/assets/img/emoji/dango.png">
            <img title=":egg:" class="emoji" src="/assets/img/emoji/egg.png">
            <img title=":bread:" class="emoji" src="/assets/img/emoji/bread.png">
            <img title=":doughnut:" class="emoji" src="/assets/img/emoji/doughnut.png">
            <img title=":custard:" class="emoji" src="/assets/img/emoji/custard.png">
            <img title=":icecream:" class="emoji" src="/assets/img/emoji/icecream.png">
            <img title=":ice_cream:" class="emoji" src="/assets/img/emoji/ice_cream.png">
            <img title=":shaved_ice:" class="emoji" src="/assets/img/emoji/shaved_ice.png">
            <img title=":birthday:" class="emoji" src="/assets/img/emoji/birthday.png">
            <img title=":cake:" class="emoji" src="/assets/img/emoji/cake.png">
            <img title=":cookie:" class="emoji" src="/assets/img/emoji/cookie.png">
            <img title=":chocolate_bar:" class="emoji" src="/assets/img/emoji/chocolate_bar.png">
            <img title=":candy:" class="emoji" src="/assets/img/emoji/candy.png">
            <img title=":lollipop:" class="emoji" src="/assets/img/emoji/lollipop.png">
            <img title=":honey_pot:" class="emoji" src="/assets/img/emoji/honey_pot.png">
            <img title=":apple:" class="emoji" src="/assets/img/emoji/apple.png">
            <img title=":green_apple:" class="emoji" src="/assets/img/emoji/green_apple.png">
            <img title=":tangerine:" class="emoji" src="/assets/img/emoji/tangerine.png">
            <img title=":lemon:" class="emoji" src="/assets/img/emoji/lemon.png">
            <img title=":cherries:" class="emoji" src="/assets/img/emoji/cherries.png">
            <img title=":grapes:" class="emoji" src="/assets/img/emoji/grapes.png">
            <img title=":watermelon:" class="emoji" src="/assets/img/emoji/watermelon.png">
            <img title=":strawberry:" class="emoji" src="/assets/img/emoji/strawberry.png">
            <img title=":peach:" class="emoji" src="/assets/img/emoji/peach.png">
            <img title=":melon:" class="emoji" src="/assets/img/emoji/melon.png">
            <img title=":banana:" class="emoji" src="/assets/img/emoji/banana.png">
            <img title=":pear:" class="emoji" src="/assets/img/emoji/pear.png">
            <img title=":pineapple:" class="emoji" src="/assets/img/emoji/pineapple.png">
            <img title=":sweet_potato:" class="emoji" src="/assets/img/emoji/sweet_potato.png">
            <img title=":eggplant:" class="emoji" src="/assets/img/emoji/eggplant.png">
            <img title=":tomato:" class="emoji" src="/assets/img/emoji/tomato.png">
            <img title=":corn:" class="emoji" src="/assets/img/emoji/corn.png">
      </p>
      <h2>Places</h2>
      <p>
            <img title=":109:" class="emoji" src="/assets/img/emoji/109.png">
            <img title=":house:" class="emoji" src="/assets/img/emoji/house.png">
            <img title=":house_with_garden:" class="emoji" src="/assets/img/emoji/house_with_garden.png">
            <img title=":school:" class="emoji" src="/assets/img/emoji/school.png">
            <img title=":office:" class="emoji" src="/assets/img/emoji/office.png">
            <img title=":post_office:" class="emoji" src="/assets/img/emoji/post_office.png">
            <img title=":hospital:" class="emoji" src="/assets/img/emoji/hospital.png">
            <img title=":bank:" class="emoji" src="/assets/img/emoji/bank.png">
            <img title=":convenience_store:" class="emoji" src="/assets/img/emoji/convenience_store.png">
            <img title=":love_hotel:" class="emoji" src="/assets/img/emoji/love_hotel.png">
            <img title=":hotel:" class="emoji" src="/assets/img/emoji/hotel.png">
            <img title=":wedding:" class="emoji" src="/assets/img/emoji/wedding.png">
            <img title=":church:" class="emoji" src="/assets/img/emoji/church.png">
            <img title=":department_store:" class="emoji" src="/assets/img/emoji/department_store.png">
            <img title=":european_post_office:" class="emoji" src="/assets/img/emoji/european_post_office.png">
            <img title=":city_sunrise:" class="emoji" src="/assets/img/emoji/city_sunrise.png">
            <img title=":city_sunset:" class="emoji" src="/assets/img/emoji/city_sunset.png">
            <img title=":japanese_castle:" class="emoji" src="/assets/img/emoji/japanese_castle.png">
            <img title=":european_castle:" class="emoji" src="/assets/img/emoji/european_castle.png">
            <img title=":tent:" class="emoji" src="/assets/img/emoji/tent.png">
            <img title=":factory:" class="emoji" src="/assets/img/emoji/factory.png">
            <img title=":tokyo_tower:" class="emoji" src="/assets/img/emoji/tokyo_tower.png">
            <img title=":japan:" class="emoji" src="/assets/img/emoji/japan.png">
            <img title=":mount_fuji:" class="emoji" src="/assets/img/emoji/mount_fuji.png">
            <img title=":sunrise_over_mountains:" class="emoji" src="/assets/img/emoji/sunrise_over_mountains.png">
            <img title=":sunrise:" class="emoji" src="/assets/img/emoji/sunrise.png">
            <img title=":stars:" class="emoji" src="/assets/img/emoji/stars.png">
            <img title=":statue_of_liberty:" class="emoji" src="/assets/img/emoji/statue_of_liberty.png">
            <img title=":bridge_at_night:" class="emoji" src="/assets/img/emoji/bridge_at_night.png">
            <img title=":carousel_horse:" class="emoji" src="/assets/img/emoji/carousel_horse.png">
            <img title=":rainbow:" class="emoji" src="/assets/img/emoji/rainbow.png">
            <img title=":ferris_wheel:" class="emoji" src="/assets/img/emoji/ferris_wheel.png">
            <img title=":fountain:" class="emoji" src="/assets/img/emoji/fountain.png">
            <img title=":roller_coaster:" class="emoji" src="/assets/img/emoji/roller_coaster.png">
            <img title=":ship:" class="emoji" src="/assets/img/emoji/ship.png">
            <img title=":speedboat:" class="emoji" src="/assets/img/emoji/speedboat.png">
            <img title=":boat:" class="emoji" src="/assets/img/emoji/boat.png">
            <img title=":sailboat:" class="emoji" src="/assets/img/emoji/sailboat.png">
            <img title=":rowboat:" class="emoji" src="/assets/img/emoji/rowboat.png">
            <img title=":anchor:" class="emoji" src="/assets/img/emoji/anchor.png">
            <img title=":rocket:" class="emoji" src="/assets/img/emoji/rocket.png">
            <img title=":airplane:" class="emoji" src="/assets/img/emoji/airplane.png">
            <img title=":helicopter:" class="emoji" src="/assets/img/emoji/helicopter.png">
            <img title=":steam_locomotive:" class="emoji" src="/assets/img/emoji/steam_locomotive.png">
            <img title=":tram:" class="emoji" src="/assets/img/emoji/tram.png">
            <img title=":mountain_railway:" class="emoji" src="/assets/img/emoji/mountain_railway.png">
            <img title=":bike:" class="emoji" src="/assets/img/emoji/bike.png">
            <img title=":aerial_tramway:" class="emoji" src="/assets/img/emoji/aerial_tramway.png">
            <img title=":suspension_railway:" class="emoji" src="/assets/img/emoji/suspension_railway.png">
            <img title=":mountain_cableway:" class="emoji" src="/assets/img/emoji/mountain_cableway.png">
            <img title=":tractor:" class="emoji" src="/assets/img/emoji/tractor.png">
            <img title=":blue_car:" class="emoji" src="/assets/img/emoji/blue_car.png">
            <img title=":oncoming_automobile:" class="emoji" src="/assets/img/emoji/oncoming_automobile.png">
            <img title=":car:" class="emoji" src="/assets/img/emoji/car.png">
            <img title=":red_car:" class="emoji" src="/assets/img/emoji/red_car.png">
            <img title=":taxi:" class="emoji" src="/assets/img/emoji/taxi.png">
            <img title=":oncoming_taxi:" class="emoji" src="/assets/img/emoji/oncoming_taxi.png">
            <img title=":articulated_lorry:" class="emoji" src="/assets/img/emoji/articulated_lorry.png">
            <img title=":bus:" class="emoji" src="/assets/img/emoji/bus.png">
            <img title=":oncoming_bus:" class="emoji" src="/assets/img/emoji/oncoming_bus.png">
            <img title=":rotating_light:" class="emoji" src="/assets/img/emoji/rotating_light.png">
            <img title=":police_car:" class="emoji" src="/assets/img/emoji/police_car.png">
            <img title=":oncoming_police_car:" class="emoji" src="/assets/img/emoji/oncoming_police_car.png">
            <img title=":fire_engine:" class="emoji" src="/assets/img/emoji/fire_engine.png">
            <img title=":ambulance:" class="emoji" src="/assets/img/emoji/ambulance.png">
            <img title=":minibus:" class="emoji" src="/assets/img/emoji/minibus.png">
            <img title=":truck:" class="emoji" src="/assets/img/emoji/truck.png">
            <img title=":train:" class="emoji" src="/assets/img/emoji/train.png">
            <img title=":station:" class="emoji" src="/assets/img/emoji/station.png">
            <img title=":train2:" class="emoji" src="/assets/img/emoji/train2.png">
            <img title=":bullettrain_front:" class="emoji" src="/assets/img/emoji/bullettrain_front.png">
            <img title=":bullettrain_side:" class="emoji" src="/assets/img/emoji/bullettrain_side.png">
            <img title=":light_rail:" class="emoji" src="/assets/img/emoji/light_rail.png">
            <img title=":monorail:" class="emoji" src="/assets/img/emoji/monorail.png">
            <img title=":railway_car:" class="emoji" src="/assets/img/emoji/railway_car.png">
            <img title=":trolleybus:" class="emoji" src="/assets/img/emoji/trolleybus.png">
            <img title=":ticket:" class="emoji" src="/assets/img/emoji/ticket.png">
            <img title=":fuelpump:" class="emoji" src="/assets/img/emoji/fuelpump.png">
            <img title=":vertical_traffic_light:" class="emoji" src="/assets/img/emoji/vertical_traffic_light.png">
            <img title=":traffic_light:" class="emoji" src="/assets/img/emoji/traffic_light.png">
            <img title=":warning:" class="emoji" src="/assets/img/emoji/warning.png">
            <img title=":construction:" class="emoji" src="/assets/img/emoji/construction.png">
            <img title=":beginner:" class="emoji" src="/assets/img/emoji/beginner.png">
            <img title=":atm:" class="emoji" src="/assets/img/emoji/atm.png">
            <img title=":slot_machine:" class="emoji" src="/assets/img/emoji/slot_machine.png">
            <img title=":busstop:" class="emoji" src="/assets/img/emoji/busstop.png">
            <img title=":barber:" class="emoji" src="/assets/img/emoji/barber.png">
            <img title=":hotsprings:" class="emoji" src="/assets/img/emoji/hotsprings.png">
            <img title=":checkered_flag:" class="emoji" src="/assets/img/emoji/checkered_flag.png">
            <img title=":crossed_flags:" class="emoji" src="/assets/img/emoji/crossed_flags.png">
            <img title=":izakaya_lantern:" class="emoji" src="/assets/img/emoji/izakaya_lantern.png">
            <img title=":moyai:" class="emoji" src="/assets/img/emoji/moyai.png">
            <img title=":circus_tent:" class="emoji" src="/assets/img/emoji/circus_tent.png">
            <img title=":performing_arts:" class="emoji" src="/assets/img/emoji/performing_arts.png">
            <img title=":round_pushpin:" class="emoji" src="/assets/img/emoji/round_pushpin.png">
            <img title=":triangular_flag_on_post:" class="emoji" src="/assets/img/emoji/triangular_flag_on_post.png">
            <img title=":jp:" class="emoji" src="/assets/img/emoji/jp.png">
            <img title=":kr:" class="emoji" src="/assets/img/emoji/kr.png">
            <img title=":cn:" class="emoji" src="/assets/img/emoji/cn.png">
            <img title=":us:" class="emoji" src="/assets/img/emoji/us.png">
            <img title=":fr:" class="emoji" src="/assets/img/emoji/fr.png">
            <img title=":es:" class="emoji" src="/assets/img/emoji/es.png">
            <img title=":it:" class="emoji" src="/assets/img/emoji/it.png">
            <img title=":ru:" class="emoji" src="/assets/img/emoji/ru.png">
            <img title=":gb:" class="emoji" src="/assets/img/emoji/gb.png">
            <img title=":uk:" class="emoji" src="/assets/img/emoji/uk.png">
            <img title=":de:" class="emoji" src="/assets/img/emoji/de.png">
      </p>
      <h2>Symbols</h2>
      <p>
            <img title=":one:" class="emoji" src="/assets/img/emoji/one.png">
            <img title=":two:" class="emoji" src="/assets/img/emoji/two.png">
            <img title=":three:" class="emoji" src="/assets/img/emoji/three.png">
            <img title=":four:" class="emoji" src="/assets/img/emoji/four.png">
            <img title=":five:" class="emoji" src="/assets/img/emoji/five.png">
            <img title=":six:" class="emoji" src="/assets/img/emoji/six.png">
            <img title=":seven:" class="emoji" src="/assets/img/emoji/seven.png">
            <img title=":eight:" class="emoji" src="/assets/img/emoji/eight.png">
            <img title=":nine:" class="emoji" src="/assets/img/emoji/nine.png">
            <img title=":keycap_ten:" class="emoji" src="/assets/img/emoji/keycap_ten.png">
            <img title=":1234:" class="emoji" src="/assets/img/emoji/1234.png">
            <img title=":zero:" class="emoji" src="/assets/img/emoji/zero.png">
            <img title=":hash:" class="emoji" src="/assets/img/emoji/hash.png">
            <img title=":symbols:" class="emoji" src="/assets/img/emoji/symbols.png">
            <img title=":arrow_backward:" class="emoji" src="/assets/img/emoji/arrow_backward.png">
            <img title=":arrow_down:" class="emoji" src="/assets/img/emoji/arrow_down.png">
            <img title=":arrow_forward:" class="emoji" src="/assets/img/emoji/arrow_forward.png">
            <img title=":arrow_left:" class="emoji" src="/assets/img/emoji/arrow_left.png">
            <img title=":capital_abcd:" class="emoji" src="/assets/img/emoji/capital_abcd.png">
            <img title=":abcd:" class="emoji" src="/assets/img/emoji/abcd.png">
            <img title=":abc:" class="emoji" src="/assets/img/emoji/abc.png">
            <img title=":arrow_lower_left:" class="emoji" src="/assets/img/emoji/arrow_lower_left.png">
            <img title=":arrow_lower_right:" class="emoji" src="/assets/img/emoji/arrow_lower_right.png">
            <img title=":arrow_right:" class="emoji" src="/assets/img/emoji/arrow_right.png">
            <img title=":arrow_up:" class="emoji" src="/assets/img/emoji/arrow_up.png">
            <img title=":arrow_upper_left:" class="emoji" src="/assets/img/emoji/arrow_upper_left.png">
            <img title=":arrow_upper_right:" class="emoji" src="/assets/img/emoji/arrow_upper_right.png">
            <img title=":arrow_double_down:" class="emoji" src="/assets/img/emoji/arrow_double_down.png">
            <img title=":arrow_double_up:" class="emoji" src="/assets/img/emoji/arrow_double_up.png">
            <img title=":arrow_down_small:" class="emoji" src="/assets/img/emoji/arrow_down_small.png">
            <img title=":arrow_heading_down:" class="emoji" src="/assets/img/emoji/arrow_heading_down.png">
            <img title=":arrow_heading_up:" class="emoji" src="/assets/img/emoji/arrow_heading_up.png">
            <img title=":leftwards_arrow_with_hook:" class="emoji" src="/assets/img/emoji/leftwards_arrow_with_hook.png">
            <img title=":arrow_right_hook:" class="emoji" src="/assets/img/emoji/arrow_right_hook.png">
            <img title=":left_right_arrow:" class="emoji" src="/assets/img/emoji/left_right_arrow.png">
            <img title=":arrow_up_down:" class="emoji" src="/assets/img/emoji/arrow_up_down.png">
            <img title=":arrow_up_small:" class="emoji" src="/assets/img/emoji/arrow_up_small.png">
            <img title=":arrows_clockwise:" class="emoji" src="/assets/img/emoji/arrows_clockwise.png">
            <img title=":arrows_counterclockwise:" class="emoji" src="/assets/img/emoji/arrows_counterclockwise.png">
            <img title=":rewind:" class="emoji" src="/assets/img/emoji/rewind.png">
            <img title=":fast_forward:" class="emoji" src="/assets/img/emoji/fast_forward.png">
            <img title=":information_source:" class="emoji" src="/assets/img/emoji/information_source.png">
            <img title=":ok:" class="emoji" src="/assets/img/emoji/ok.png">
            <img title=":twisted_rightwards_arrows:" class="emoji" src="/assets/img/emoji/twisted_rightwards_arrows.png">
            <img title=":repeat:" class="emoji" src="/assets/img/emoji/repeat.png">
            <img title=":repeat_one:" class="emoji" src="/assets/img/emoji/repeat_one.png">
            <img title=":new:" class="emoji" src="/assets/img/emoji/new.png">
            <img title=":top:" class="emoji" src="/assets/img/emoji/top.png">
            <img title=":up:" class="emoji" src="/assets/img/emoji/up.png">
            <img title=":cool:" class="emoji" src="/assets/img/emoji/cool.png">
            <img title=":free:" class="emoji" src="/assets/img/emoji/free.png">
            <img title=":ng:" class="emoji" src="/assets/img/emoji/ng.png">
            <img title=":cinema:" class="emoji" src="/assets/img/emoji/cinema.png">
            <img title=":koko:" class="emoji" src="/assets/img/emoji/koko.png">
            <img title=":signal_strength:" class="emoji" src="/assets/img/emoji/signal_strength.png">
            <img title=":u5272:" class="emoji" src="/assets/img/emoji/u5272.png">
            <img title=":u5408:" class="emoji" src="/assets/img/emoji/u5408.png">
            <img title=":u55b6:" class="emoji" src="/assets/img/emoji/u55b6.png">
            <img title=":u6307:" class="emoji" src="/assets/img/emoji/u6307.png">
            <img title=":u6708:" class="emoji" src="/assets/img/emoji/u6708.png">
            <img title=":u6709:" class="emoji" src="/assets/img/emoji/u6709.png">
            <img title=":u6e80:" class="emoji" src="/assets/img/emoji/u6e80.png">
            <img title=":u7121:" class="emoji" src="/assets/img/emoji/u7121.png">
            <img title=":u7533:" class="emoji" src="/assets/img/emoji/u7533.png">
            <img title=":u7a7a:" class="emoji" src="/assets/img/emoji/u7a7a.png">
            <img title=":u7981:" class="emoji" src="/assets/img/emoji/u7981.png">
            <img title=":sa:" class="emoji" src="/assets/img/emoji/sa.png">
            <img title=":restroom:" class="emoji" src="/assets/img/emoji/restroom.png">
            <img title=":mens:" class="emoji" src="/assets/img/emoji/mens.png">
            <img title=":womens:" class="emoji" src="/assets/img/emoji/womens.png">
            <img title=":baby_symbol:" class="emoji" src="/assets/img/emoji/baby_symbol.png">
            <img title=":no_smoking:" class="emoji" src="/assets/img/emoji/no_smoking.png">
            <img title=":parking:" class="emoji" src="/assets/img/emoji/parking.png">
            <img title=":wheelchair:" class="emoji" src="/assets/img/emoji/wheelchair.png">
            <img title=":metro:" class="emoji" src="/assets/img/emoji/metro.png">
            <img title=":baggage_claim:" class="emoji" src="/assets/img/emoji/baggage_claim.png">
            <img title=":accept:" class="emoji" src="/assets/img/emoji/accept.png">
            <img title=":wc:" class="emoji" src="/assets/img/emoji/wc.png">
            <img title=":potable_water:" class="emoji" src="/assets/img/emoji/potable_water.png">
            <img title=":put_litter_in_its_place:" class="emoji" src="/assets/img/emoji/put_litter_in_its_place.png">
            <img title=":secret:" class="emoji" src="/assets/img/emoji/secret.png">
            <img title=":congratulations:" class="emoji" src="/assets/img/emoji/congratulations.png">
            <img title=":m:" class="emoji" src="/assets/img/emoji/m.png">
            <img title=":passport_control:" class="emoji" src="/assets/img/emoji/passport_control.png">
            <img title=":left_luggage:" class="emoji" src="/assets/img/emoji/left_luggage.png">
            <img title=":customs:" class="emoji" src="/assets/img/emoji/customs.png">
            <img title=":ideograph_advantage:" class="emoji" src="/assets/img/emoji/ideograph_advantage.png">
            <img title=":cl:" class="emoji" src="/assets/img/emoji/cl.png">
            <img title=":sos:" class="emoji" src="/assets/img/emoji/sos.png">
            <img title=":id:" class="emoji" src="/assets/img/emoji/id.png">
            <img title=":no_entry_sign:" class="emoji" src="/assets/img/emoji/no_entry_sign.png">
            <img title=":underage:" class="emoji" src="/assets/img/emoji/underage.png">
            <img title=":no_mobile_phones:" class="emoji" src="/assets/img/emoji/no_mobile_phones.png">
            <img title=":do_not_litter:" class="emoji" src="/assets/img/emoji/do_not_litter.png">
            <img title=":non-potable_water:" class="emoji" src="/assets/img/emoji/non-potable_water.png">
            <img title=":no_bicycles:" class="emoji" src="/assets/img/emoji/no_bicycles.png">
            <img title=":no_pedestrians:" class="emoji" src="/assets/img/emoji/no_pedestrians.png">
            <img title=":children_crossing:" class="emoji" src="/assets/img/emoji/children_crossing.png">
            <img title=":no_entry:" class="emoji" src="/assets/img/emoji/no_entry.png">
            <img title=":eight_spoked_asterisk:" class="emoji" src="/assets/img/emoji/eight_spoked_asterisk.png">
            <img title=":eight_pointed_black_star:" class="emoji" src="/assets/img/emoji/eight_pointed_black_star.png">
            <img title=":heart_decoration:" class="emoji" src="/assets/img/emoji/heart_decoration.png">
            <img title=":vs:" class="emoji" src="/assets/img/emoji/vs.png">
            <img title=":vibration_mode:" class="emoji" src="/assets/img/emoji/vibration_mode.png">
            <img title=":mobile_phone_off:" class="emoji" src="/assets/img/emoji/mobile_phone_off.png">
            <img title=":chart:" class="emoji" src="/assets/img/emoji/chart.png">
            <img title=":currency_exchange:" class="emoji" src="/assets/img/emoji/currency_exchange.png">
            <img title=":aries:" class="emoji" src="/assets/img/emoji/aries.png">
            <img title=":taurus:" class="emoji" src="/assets/img/emoji/taurus.png">
            <img title=":gemini:" class="emoji" src="/assets/img/emoji/gemini.png">
            <img title=":cancer:" class="emoji" src="/assets/img/emoji/cancer.png">
            <img title=":leo:" class="emoji" src="/assets/img/emoji/leo.png">
            <img title=":virgo:" class="emoji" src="/assets/img/emoji/virgo.png">
            <img title=":libra:" class="emoji" src="/assets/img/emoji/libra.png">
            <img title=":scorpius:" class="emoji" src="/assets/img/emoji/scorpius.png">
            <img title=":sagittarius:" class="emoji" src="/assets/img/emoji/sagittarius.png">
            <img title=":capricorn:" class="emoji" src="/assets/img/emoji/capricorn.png">
            <img title=":aquarius:" class="emoji" src="/assets/img/emoji/aquarius.png">
            <img title=":pisces:" class="emoji" src="/assets/img/emoji/pisces.png">
            <img title=":ophiuchus:" class="emoji" src="/assets/img/emoji/ophiuchus.png">
            <img title=":six_pointed_star:" class="emoji" src="/assets/img/emoji/six_pointed_star.png">
            <img title=":negative_squared_cross_mark:" class="emoji" src="/assets/img/emoji/negative_squared_cross_mark.png">
            <img title=":a:" class="emoji" src="/assets/img/emoji/a.png">
            <img title=":b:" class="emoji" src="/assets/img/emoji/b.png">
            <img title=":ab:" class="emoji" src="/assets/img/emoji/ab.png">
            <img title=":o2:" class="emoji" src="/assets/img/emoji/o2.png">
            <img title=":diamond_shape_with_a_dot_inside:" class="emoji" src="/assets/img/emoji/diamond_shape_with_a_dot_inside.png">
            <img title=":recycle:" class="emoji" src="/assets/img/emoji/recycle.png">
            <img title=":end:" class="emoji" src="/assets/img/emoji/end.png">
            <img title=":on:" class="emoji" src="/assets/img/emoji/on.png">
            <img title=":soon:" class="emoji" src="/assets/img/emoji/soon.png">
            <img title=":clock1:" class="emoji" src="/assets/img/emoji/clock1.png">
            <img title=":clock130:" class="emoji" src="/assets/img/emoji/clock130.png">
            <img title=":clock10:" class="emoji" src="/assets/img/emoji/clock10.png">
            <img title=":clock1030:" class="emoji" src="/assets/img/emoji/clock1030.png">
            <img title=":clock11:" class="emoji" src="/assets/img/emoji/clock11.png">
            <img title=":clock1130:" class="emoji" src="/assets/img/emoji/clock1130.png">
            <img title=":clock12:" class="emoji" src="/assets/img/emoji/clock12.png">
            <img title=":clock1230:" class="emoji" src="/assets/img/emoji/clock1230.png">
            <img title=":clock2:" class="emoji" src="/assets/img/emoji/clock2.png">
            <img title=":clock230:" class="emoji" src="/assets/img/emoji/clock230.png">
            <img title=":clock3:" class="emoji" src="/assets/img/emoji/clock3.png">
            <img title=":clock330:" class="emoji" src="/assets/img/emoji/clock330.png">
            <img title=":clock4:" class="emoji" src="/assets/img/emoji/clock4.png">
            <img title=":clock430:" class="emoji" src="/assets/img/emoji/clock430.png">
            <img title=":clock5:" class="emoji" src="/assets/img/emoji/clock5.png">
            <img title=":clock530:" class="emoji" src="/assets/img/emoji/clock530.png">
            <img title=":clock6:" class="emoji" src="/assets/img/emoji/clock6.png">
            <img title=":clock630:" class="emoji" src="/assets/img/emoji/clock630.png">
            <img title=":clock7:" class="emoji" src="/assets/img/emoji/clock7.png">
            <img title=":clock730:" class="emoji" src="/assets/img/emoji/clock730.png">
            <img title=":clock8:" class="emoji" src="/assets/img/emoji/clock8.png">
            <img title=":clock830:" class="emoji" src="/assets/img/emoji/clock830.png">
            <img title=":clock9:" class="emoji" src="/assets/img/emoji/clock9.png">
            <img title=":clock930:" class="emoji" src="/assets/img/emoji/clock930.png">
            <img title=":heavy_dollar_sign:" class="emoji" src="/assets/img/emoji/heavy_dollar_sign.png">
            <img title=":copyright:" class="emoji" src="/assets/img/emoji/copyright.png">
            <img title=":registered:" class="emoji" src="/assets/img/emoji/registered.png">
            <img title=":tm:" class="emoji" src="/assets/img/emoji/tm.png">
            <img title=":x:" class="emoji" src="/assets/img/emoji/x.png">
            <img title=":heavy_exclamation_mark:" class="emoji" src="/assets/img/emoji/heavy_exclamation_mark.png">
            <img title=":bangbang:" class="emoji" src="/assets/img/emoji/bangbang.png">
            <img title=":interrobang:" class="emoji" src="/assets/img/emoji/interrobang.png">
            <img title=":o:" class="emoji" src="/assets/img/emoji/o.png">
            <img title=":heavy_multiplication_x:" class="emoji" src="/assets/img/emoji/heavy_multiplication_x.png">
            <img title=":heavy_plus_sign:" class="emoji" src="/assets/img/emoji/heavy_plus_sign.png">
            <img title=":heavy_minus_sign:" class="emoji" src="/assets/img/emoji/heavy_minus_sign.png">
            <img title=":heavy_division_sign:" class="emoji" src="/assets/img/emoji/heavy_division_sign.png">
            <img title=":white_flower:" class="emoji" src="/assets/img/emoji/white_flower.png">
            <img title=":100:" class="emoji" src="/assets/img/emoji/100.png">
            <img title=":heavy_check_mark:" class="emoji" src="/assets/img/emoji/heavy_check_mark.png">
            <img title=":ballot_box_with_check:" class="emoji" src="/assets/img/emoji/ballot_box_with_check.png">
            <img title=":radio_button:" class="emoji" src="/assets/img/emoji/radio_button.png">
            <img title=":link:" class="emoji" src="/assets/img/emoji/link.png">
            <img title=":curly_loop:" class="emoji" src="/assets/img/emoji/curly_loop.png">
            <img title=":wavy_dash:" class="emoji" src="/assets/img/emoji/wavy_dash.png">
            <img title=":part_alternation_mark:" class="emoji" src="/assets/img/emoji/part_alternation_mark.png">
            <img title=":trident:" class="emoji" src="/assets/img/emoji/trident.png">
            <img title=":black_square:" class="emoji" src="/assets/img/emoji/black_square.png">
            <img title=":white_square:" class="emoji" src="/assets/img/emoji/white_square.png">
            <img title=":white_check_mark:" class="emoji" src="/assets/img/emoji/white_check_mark.png">
            <img title=":black_square_button:" class="emoji" src="/assets/img/emoji/black_square_button.png">
            <img title=":white_square_button:" class="emoji" src="/assets/img/emoji/white_square_button.png">
            <img title=":black_circle:" class="emoji" src="/assets/img/emoji/black_circle.png">
            <img title=":white_circle:" class="emoji" src="/assets/img/emoji/white_circle.png">
            <img title=":red_circle:" class="emoji" src="/assets/img/emoji/red_circle.png">
            <img title=":large_blue_circle:" class="emoji" src="/assets/img/emoji/large_blue_circle.png">
            <img title=":large_blue_diamond:" class="emoji" src="/assets/img/emoji/large_blue_diamond.png">
            <img title=":large_orange_diamond:" class="emoji" src="/assets/img/emoji/large_orange_diamond.png">
            <img title=":small_blue_diamond:" class="emoji" src="/assets/img/emoji/small_blue_diamond.png">
            <img title=":small_orange_diamond:" class="emoji" src="/assets/img/emoji/small_orange_diamond.png">
            <img title=":small_red_triangle:" class="emoji" src="/assets/img/emoji/small_red_triangle.png">
            <img title=":small_red_triangle_down:" class="emoji" src="/assets/img/emoji/small_red_triangle_down.png">
            <img title=":shipit:" class="emoji" src="/assets/img/emoji/shipit.png">
      </p>
</div>